server.port=8081
spring.application.name=trip-core-service
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
spring.threads.virtual.enabled=true

api.openweather.url=https://api.openweathermap.org/data/2.5
api.openweather.key=${API_OPENWEATHER_KEY:}

api.unsplash.key=${API_UNSPLASH_KEY:}

api.gemini.model=${API_GEMINI_MODEL:gemini-2.5-flash}
api.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/${api.gemini.model}:generateContent
api.gemini.key=${API_GEMINI_KEY:}

spring.datasource.url=jdbc:postgresql://${DB_IP:34.116.184.100}:5432/tripify-backend
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_JWK_SET_URI:http://localhost:9000/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER_URI:http://localhost:9000}

spring.profiles.include=secrets
