package com.tripify.backend.controller;

import com.tripify.backend.dto.SaveTripPlanRequest;
import com.tripify.backend.dto.SavedTripPlanResponse;
import com.tripify.backend.dto.TripPlanResponse;
import com.tripify.backend.model.AppUser;
import com.tripify.backend.service.AuthService;
import com.tripify.backend.service.TripPlannerService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.ExceptionHandler;
import jakarta.validation.Valid;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/trips")
@Tag(name = "Trip Planner", description = "Endpoints for planning trips using multiple data sources")
public class TripController {

    private final TripPlannerService tripPlannerService;
    private final AuthService authService;

    public TripController(TripPlannerService tripPlannerService, AuthService authService) {
        this.tripPlannerService = tripPlannerService;
        this.authService = authService;
    }

    @GetMapping("/plan/{city}")
    @Operation(summary = "Plan a trip", description = "Fetches weather and interesting places for a given city asynchronously.")
    public ResponseEntity<?> planTrip(
            @PathVariable String city,
            @org.springframework.web.bind.annotation.RequestParam(defaultValue = "1") int days,
            @org.springframework.web.bind.annotation.RequestParam(defaultValue = "relaxed") String pace,
            @RequestHeader(value = HttpHeaders.AUTHORIZATION, required = false) String authorization
    ) {
        AppUser user = getAuthenticatedUser(authorization);
        if (user == null) {
            return unauthorized();
        }

        TripPlanResponse response = tripPlannerService.planTrip(city, days, pace, user);
        return ResponseEntity.ok(response);
    }

    @GetMapping("/mine")
    @Operation(summary = "Get saved trip plans", description = "Returns trip plans generated by the current user.")
    public ResponseEntity<?> getSavedPlans(
            @RequestHeader(value = HttpHeaders.AUTHORIZATION, required = false) String authorization
    ) {
        AppUser user = getAuthenticatedUser(authorization);
        if (user == null) {
            return unauthorized();
        }

        List<SavedTripPlanResponse> response = tripPlannerService.getSavedPlans(user);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/mine")
    @Operation(summary = "Save generated trip plan", description = "Saves a generated trip plan for the current user.")
    public ResponseEntity<?> savePlan(
            @RequestHeader(value = HttpHeaders.AUTHORIZATION, required = false) String authorization,
            @Valid @RequestBody SaveTripPlanRequest request
    ) {
        AppUser user = getAuthenticatedUser(authorization);
        if (user == null) {
            return unauthorized();
        }

        return ResponseEntity.status(HttpStatus.CREATED).body(tripPlannerService.savePlan(user, request));
    }

    @DeleteMapping("/mine/{planId}")
    @Operation(summary = "Delete saved trip plan", description = "Deletes a saved trip plan owned by the current user.")
    public ResponseEntity<?> deleteSavedPlan(
            @RequestHeader(value = HttpHeaders.AUTHORIZATION, required = false) String authorization,
            @PathVariable Long planId
    ) {
        AppUser user = getAuthenticatedUser(authorization);
        if (user == null) {
            return unauthorized();
        }

        tripPlannerService.deleteSavedPlan(user, planId);
        return ResponseEntity.noContent().build();
    }

    private AppUser getAuthenticatedUser(String authorization) {
        String token = authService.extractBearerToken(authorization);
        if (token == null) {
            return null;
        }
        return authService.findAppUserByToken(token).orElse(null);
    }

    private ResponseEntity<Map<String, String>> unauthorized() {
        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error", "Zaloguj się, aby generować plany podróży."));
    }

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<Map<String, String>> handleIllegalArgument(IllegalArgumentException exception) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(Map.of("error", exception.getMessage()));
    }
}
